import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Context from "../components/Provider";
import { ClerkProvider } from "@clerk/nextjs";
import { NavBar } from "@/components/NavBar";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const dmMono = DM_Sans({
  variable: "--font-dm-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${dmSans.variable} ${dmMono.variable} antialiased`}>
          <Context>
            <NavBar />
            <div className="pt-12">
              {children}
            </div>
          </Context>
        </body>
      </html>
    </ClerkProvider>
  );
}
